### ISSUE TITLE
Creating basic Structure which supports Configuration Over Redoing Things

### ISSUE THREAD

**Issue by maektwain** [upscaletech/upscale-ui#2]
The basic and the essential structure for the web application or the upscale-ui needs to developed there are few things which we need to start and do it before we actually start the collaborations from outside community 
1. We need basic methods to be implemented such as login, authentication and session storage
2. Services which we need to customise like using elastic search and error codes , creating issues directly from the browser, 
3. We use web socket to record customer behaviour, analysis and sending message between applications to different clients so proper methods should  be implemented 
4. All pre-req methods should be introduced as service
5. Like for e.g. we have created a list of arrays which gives us all the API which are there with the system which we will also provide to show customer 
6. We need to implemented basic structure to the app so that everyone can understand what is happening in the app

Tech 

We can use AngularJS which seems fairly easy and productive or react js 

We need a singular approach where we can develop this application because we have three different context which are as
1. Partner 
2. Customer 
3. Sellers

So providing different context is going to be complex and not easy but with above segregated approach will work

Partners will have different set of API and so as other two have  

Conclusion 
What we want is the proper structure of the application with proper navigated and classified design approach with minimum clutter 

Thanks

**Comment by mit2u** [comment]
@brianoconner777 Hi I  am looking into the features side, We can sit for a hangout discussions biweekly...reply with ur preferred timings.

**Comment by maektwain** [comment]
@brianoconner777  Please update your schedule on tech.team@theupscale.in i have created your email address saurabh.garg@upscale.co.in with password upscale123SDF here are the mail settings you can use to log in 

IMAP
Incoming Server Name : imappro.zoho.com
Port : 993
Require SSL : Yes
Username : you@yourdomain.com
POP
Incoming Server Name : poppro.zoho.com
Port : 995
Require SSL : Yes
Username : you@yourdomain.com
Outgoing / SMTP
Outgoing Server Name: smtp.zoho.com
Port : 465 with SSL or 587 with TLS
Require Authentication: Yes

You can configure your mail on any devices or client 

Tech.team@theupscale.in is going to be centra group discussion board for community

**Comment by maektwain** [comment]
The structure of the application should address following issue and resolve them 

1. First it should not be many folders for every operation every folder cluttered approach 
Once you have to many folders and files in them you will end up scrolling them a lot

1. Component Approach Might Work That every single folder will have component folder to it like 

``` json

app/
----- shared/   // acts as reusable components or partials of our site
---------- sidebar/
--------------- sidebarDirective.js
--------------- sidebarView.html
---------- article/
--------------- articleDirective.js
--------------- articleView.html
----- components/   // each component is treated as a mini Angular app
---------- home/
--------------- homeController.js
--------------- homeService.js
--------------- homeView.html
---------- blog/
--------------- blogController.js
--------------- blogService.js
--------------- blogView.html
----- app.module.js
----- app.routes.js
assets/
----- img/      // Images and icons for your app
----- css/      // All styles and style related files (SCSS or LESS files)
----- js/       // JavaScript files written for your app that are not for angular
----- libs/     // Third-party libraries such as jQuery, Moment, Underscore, etc.
index.html
```

1. Index.html should live in the root of the project folder 

1. Assets

1. Shared 

1. Components 

@brianoconner777

**Comment by maektwain** [comment]
Focus over Modular Approach 
1. Code Maintainability 
1. Debugging 
1. Scalable
1. Testing

**Comment by maektwain** [comment]
@brianoconner777
